### ISSUE TITLE
The border is not drawn on some windows

### ISSUE THREAD

**Issue by TAforever** [natemaia/dk#1]
Until recently, this problem most often happened with  steam window, but after today's update it also started happening with telegram window.

**Comment by natemaia** [comment]
Would you be able to show another video or screenshot of the issue in action. I know I've seen one already but I can't seem to reproduce this.

**Comment by TAforever** [comment]
This bug is very insidious and is not reproduced in 100% of cases. In the video you can see how the steam window appears without borders, but if, for example, I open a terminal and close it, then the border will appear.

https://github.com/natemaia/dk/assets/52626363/5f1c4f52-25ad-48ff-bb2e-763160f0d9f2

![telgram_without_border](https://github.com/natemaia/dk/assets/52626363/7367c334-1d9f-4f9f-9ae2-e1d4e8226036)

**Comment by natemaia** [comment]
Sorry I wasn't able to catch your vids, this is basically what I'm getting

https://imgur.com/eFB9ypZ

**Comment by natemaia** [comment]
So I managed to reproduce it finally, I didn't pay attention and see that you had small gaps as well, for whatever reason this seems to be why it wasn't happening for me. After that I did a bit of messing around to find the best way to handle it. In the most recent commit [8e6f1dd](https://github.com/natemaia/dk/commit/8e6f1ddac807ac918a6dab2d7ba8bc3a9f2d123f) it seems to be fixed.

Please let me know how it goes.

**Comment by TAforever** [comment]
Looks like the problem has been fixed, great!
