### ISSUE TITLE
When restarting dk there is a padding/gaps at the top 

### ISSUE THREAD

**Issue by selfish-dot** [natemaia/dk#14]
I'm running Debian 12, with dk v2.3 I just updated dk and when I restart the window manager a gap appears at the top of the screen, and every time I restart the gap increases, this didn't happen previous to updating. I'm running polybar from the Debian repositories. It's my first time posting an issue, so please tell me what can I do to provide you with more information to test this.

![2024-Sep-06-13-46](https://github.com/user-attachments/assets/28f15154-c9e1-4bc5-ad7d-8b6e88b7a7e7)

Also, I made the update following the steps on the doc

**Comment by selfish-dot** [comment]
Hi, I did some testing. I think is an issue with starting polybar within dkrc. I just commented out the line that launched polybar on my dkrc and put it on .xinitrc and that solved the problem. Hope it helps to do some testing

**Comment by TAforever** [comment]
This is not a dk bug, this is standard behavior of polybar. To avoid this, run polybar using a script as specified in archwiki     https://wiki.archlinux.org/title/Polybar#Running_with_a_window_manager  or add these two lines to dkrc:
```bash
killall polybar
polybar example &
```

**Comment by selfish-dot** [comment]
Hi, thank you. You were right! Sorry for opening this without doing proper research

**Comment by natemaia** [comment]
No need to be sorry, thanks Theodor for the help!
