### ISSUE TITLE
Under certain circumstances, new windows do not receive focus

### ISSUE THREAD

**Issue by TAforever** [natemaia/dk#2]
If I have a window open on the 3rd workspace (steam for example) and while on another workspace I launch programs that should appear on the 3rd workspace, then they do not receive focus when launched. I discovered this bug when starting retroarch (it starts in full screen mode by default) and I couldn’t interact with the window in any way.

https://github.com/natemaia/dk/assets/52626363/a4747167-e01e-456b-a597-cc42cd3cb5aa

**Comment by natemaia** [comment]
I think I've fixed this in the recent commit, there's a new issue of windows not always being drawn when they should but I'm gonna backport the new fixes to an older commit without the issues.

**Comment by TAforever** [comment]
This problem has been fixed, but #3 still exists
