### ISSUE TITLE
In Firefox file chooser dialog does not appear

### ISSUE THREAD

**Issue by TAforever** [natemaia/dk#3]
If I select “save object as” in the context menu, the file chooser dialog window does not appear, but if I switch to another workspace and then back, the window appears.

https://github.com/natemaia/dk/assets/52626363/ff7dff93-82c3-4bda-9a90-61b9443c810f

**Comment by natemaia** [comment]
This is a recently introduced issue, see my response in #2. I'm on it

**Comment by TAforever** [comment]
I noticed that this problem also exists in Telegram: if you click on a photo or video, the Telegram viewer window does not appear.

**Comment by TAforever** [comment]
In firefox the problem is fixed, but in telegram if you click on any photo or video, dk crashes

**Comment by natemaia** [comment]
Sorry about, I'll get it fixed.

**Comment by natemaia** [comment]
Latest commit should have it fixed

**Comment by TAforever** [comment]
yes, everything is fixed
