### ISSUE TITLE
The bug with drawing the bottom border of the polkit window has returned again (i use gnome-polkit)

### ISSUE THREAD

**Issue by TAforever** [natemaia/dk#4]
![polkit_border](https://github.com/natemaia/dk/assets/52626363/c98f7fea-ce05-4814-89e2-37813bb954c1)

**Comment by natemaia** [comment]
Sorry about that, fixed here
https://github.com/natemaia/dk/commit/aded1ceb80f837336029691d50cb5daba29f2334#diff-d3677fbf9b172c96762664a29fd91b6165c4f9a1550655800d8a320a400ff05dL1894-L1900

**Comment by TAforever** [comment]
Problem solved, thanks
