### ISSUE TITLE
In some cases retroarch does not launch games

### ISSUE THREAD

**Issue by TAforever** [natemaia/dk#5]
Perhaps this problem is somehow related to https://github.com/natemaia/dk/issues/2. Everything related to games is tied to my workspace 3. This bug is not reproduced in 100% of cases. If I have a window open on workspace 3, then when I try to start the game in retroarch, the game does not start, but if I switch to another workspace, and then back, the game will start.

https://github.com/natemaia/dk/assets/52626363/709b66ec-8eb6-430d-98c4-cc8d9a80c4d5

**Comment by natemaia** [comment]
I'll look into this

**Comment by natemaia** [comment]
Can you check with the recent commit, I'm doing the mapping of windows immediately rather than delay it until refresh. This has other issues but I want to make sure it fixes it before I deal with them.

**Comment by TAforever** [comment]
If I understand you correctly, then this bug is reproduced on the last commit, as soon as a new commit is released I immediately update

**Comment by natemaia** [comment]
apologies, I just pushed it

**Comment by TAforever** [comment]
> apologies, I just pushed it

I tested almost all games for different consoles and did not reproduce this bug, should I close this issue?

**Comment by TAforever** [comment]
Stupid question... I just thought that you wanted to fix something else in this issue

**Comment by natemaia** [comment]
No absolutely it can be closed. I'm gonna use this approach in more places I think, refreshing in place rather than differing them till later. It was done to save on redraws and flickering when many events happened in a short period.

The only issue I noticed is when a new window is opened while a fullscreen window is active on the workspace it causes a flicker. Not sure if it's all the time or just occasionally but it's an easy fix.

**Comment by TAforever** [comment]
> No absolutely it can be closed. I'm gonna use this approach in more places I think, refreshing in place rather than differing them till later. It was done to save on redraws and flickering when many events happened in a short period.
> 
> The only issue I noticed is when a new window is opened while a fullscreen window is active on the workspace it causes a flicker. Not sure if it's all the time or just occasionally but it's an easy fix.

Since you mentioned flickering, I would like to inform you that the polybar flickers when the system boots when it appears. I didn't open a separate issue because the problem is too insignificant, but if you have the opportunity to fix this, that would be great.

**Comment by natemaia** [comment]
I can look into it, does it only happen on startup?

**Comment by TAforever** [comment]
Yes, this happens at startup, there is a slight “blinking”, otherwise the polybar works fine

**Comment by natemaia** [comment]
Please try the latest commit, I think it's either fixed or I'm just unable to reproduce.

**Comment by TAforever** [comment]
I tried it, unfortunately this glitch is reproducible, but I don't think there is any need to worry about it, the problem is too minor

**Comment by natemaia** [comment]
@TAforever Can you post your polybar config and dkrc (if used for starting polybar)?

If I can get some idea of what and where it's happening then I can do a lot more but right now it's a crap shoot and I don't want to mess around with hacky solutions unless absolutely necessary.

**Comment by natemaia** [comment]
A video of it would be helpful though I'm not sure how possible that is for you.

**Comment by natemaia** [comment]
I suppose a better way of doing this would be: can you run the default bar with polybar and does it still happen?

**Comment by TAforever** [comment]
Yes, with the default config the problem is reproduced, but I repeat once again: I think that you should not worry about this, because the problem is too minor, it only happens when loading and lasts a split second

**Comment by natemaia** [comment]
okie

**Comment by TAforever** [comment]
Today I noticed that polybar no longer blinks when it appears. Thanks for the fix

**Comment by natemaia** [comment]
Great to hear
