### ISSUE TITLE
Polybar xworkspaces doesn't update.

### ISSUE THREAD

**Issue by cronyakatsuki** [natemaia/dk#6]
Hi, I'm using polybar with dk and the xworkspaces module doesn't update at times.

What I mean by that is that if I'm on 1st workspace and then press the keybinding and move to second workspace polybar module still show's I'm on first one.

The issue doesn't always happen but when it does it's annoying.

**Comment by natemaia** [comment]
I think this should be fixed with the latest commit. Please let me know if you notice anything.

**Comment by cronyakatsuki** [comment]
Latest commit fixed the issue.

**Comment by cronyakatsuki** [comment]
Sorry, closed prematurely. 

Now the issue happen's if I close a window in a workspace, it will always say on the polybar module that there is a window opened on it ( I had a scratch window there that's why, maybe make the scratch command sticky the scratch windows? ) and when I focus on the workspace the module won't show that I focused on it but will continue saying that I'm on the last workspace.

It worked fine first couple of minutes but then it started miss behaving again.

Here is how I manage to make it trigger the issue.

I start from the first workspace, change to second, and then to third. I then repeate the proccess in reverse and do it a couplle of times. After about 3rd time of doing that it will stop focusing on the second workspace until I focus on it 2 times.

Another way I'm able to trigger the issues is by using the `dkcmd ws view last` command if run a little too fast.

Like that I can trigger the issue pretty much on will.

**Comment by TAforever** [comment]
This is very strange, I also use polybar with the xworkspaces module, but for me it works flawlessly, but I don’t use scratchpads, maybe this is the reason?

**Comment by cronyakatsuki** [comment]
> This is very strange, I also use polybar with the xworkspaces module, but for me it works flawlessly, but I don’t use scratchpads, maybe this is the reason?

No, I tried to used them later on it happens without them.

Maybe it's because I'm on gentoo?

**Comment by TAforever** [comment]
I can’t say anything about this, because I use a different distro, but perhaps this information will be useful to the developer

**Comment by cronyakatsuki** [comment]
> I can’t say anything about this, because I use a different distro, but perhaps this information will be useful to the developer

What version of dk are you using? I'm using the latest git commit version.

**Comment by TAforever** [comment]
I'm also using the latest commit, but  for testing I installed version 1.9  and didn't notice any glitches either

**Comment by natemaia** [comment]
I mean I can add more flushing of the X event buffer after changes to relevant properties (ewmh atoms) and hope for the best.

Like @TAforever I'm not getting this, even the extra flushing really shouldn't be needed but I'm probably missing something. I'll push a commit soon here and we'll see how it goes.

**Comment by natemaia** [comment]
Try out the latest commit and let me know if you still have the issue @cronyakatsuki

**Comment by cronyakatsuki** [comment]
> Try out the latest commit and let me know if you still have the issue @cronyakatsuki

With the latest commit the issue doesn't happen anymore when changing beetween workspaces that are either all empty, or have atleast one window.

By that I mean that when I change between a workspadce with a window to one that doesn't have any window xworkspaces plugin sometimes won't focus on it until I spawn a window in that workspace, when it will show in the plugin that I'm focused on the workspace.

If I change between workspaces that either are not empty or are empty now it focuses corretly on the workspace in the plugin.

**Comment by natemaia** [comment]
Would you be willing to post your polybar config?

I've tried as you say but still not getting it, is there something I'm doing wrong? I'll just keep looking

**Comment by cronyakatsuki** [comment]
Here is my polybar [config](https://upfast.cronyakatsuki.xyz/files/config.ini). It uses a lot of custom script's to get some info which you can disable for testing purposes.

**Comment by cronyakatsuki** [comment]
I'm really sorry, it seems that it was gentoo's fault.

The stable polybar version in gentoo seem's to have been bug ridden and after updating to a testing version the xworkspaces module work's without any issues.

Once again sorry for having you try to fix an issue that didn't exist in the first place.

**Comment by natemaia** [comment]
Excellent, I was starting to suspect something like that cause it just wasn't adding up.

Cheers
