### ISSUE TITLE
Problems with retroarch

### ISSUE THREAD

**Issue by TAforever** [natemaia/dk#7]
I noticed strange things in the work of retroarch, such as the inability to enter full-screen mode when starting the game, also if there is a window in the workspace, the “fullscreen” retroarch window becomes even smaller

https://github.com/natemaia/dk/assets/52626363/8636f69a-e206-4494-af80-7ca76dd963c7

**Comment by natemaia** [comment]
Okay I think this is just due to the recent change, I'll make sure a full refresh is done when we do a fullscreen switch

**Comment by natemaia** [comment]
I pushed a small commit, I'm not entirely sure where the issue is happening but this could fix it.

**Comment by TAforever** [comment]
Unfortunately, the problem is not fixed

**Comment by natemaia** [comment]
Ok I've pushed another commit with a few changes around fullscreen and window focus. Apologies for the runaround but I've installed retroarch and got it setup somewhat *(dolphin core running LoZ-WW)* and I'm not seeing the issue happen.

If it's still happening I'm wondering if you can dump your dkrc and some steps to reproduce? I can kinda see what is going on from the video but I'm struggling to get it happening. Might also be that the last changes stopped it.

**Comment by TAforever** [comment]
The problem is completely fixed

**Comment by natemaia** [comment]
Awesome, I apologize for the issues, trying to optimize and simplify by diverting things to the refresh loop is what I've been moving towards but I'll make notes that some things like fullscreen window handling can't be done that way *(so this doesn't happen again.. again in the future :) )*. You're patience and help with issues like this helps me learn Xorg and is greatly appreciated.

Cheers,
Nathaniel

**Comment by TAforever** [comment]
Sir, I am  glad that I can at least help you with something, but don’t apologize about issues. Bugs may only be absent in the Hello World program ;)

**Comment by natemaia** [comment]
Thank you sir, people like you keep me going and wanting to improve projects.

Cheers
