### ISSUE TITLE
Scratch command doesnt toggle

### ISSUE THREAD

**Issue by tony-cannibal** [natemaia/dk#8]
"dkcmd win scratch" doesnt send current selected window to the scratchpad, it closes dk and sends me back to lightdm

**Comment by natemaia** [comment]
This should be fixed with the latest commit, apologies for the issues.

**Comment by tony-cannibal** [comment]
Thank you, dk is no longer crashing. One last last thing, I can't toggle on existing scratchpads on empty work spaces. I want to know if this the intended behavior, if it is then there is no problem.

**Comment by natemaia** [comment]
No that is definitely not intended, I'm looking into it and will have a fix soon.

**Comment by natemaia** [comment]
This should be all cleared up with the latest commit, with some other stuff I noticed wasn't working correctly when messing around with scratch windows.

**Comment by tony-cannibal** [comment]
Thank you, the scratchpads are working correctly.
