### ISSUE TITLE
Windows below bar

### ISSUE THREAD

**Issue by ACR-Jeff** [natemaia/dk#9]
What I have here is a new install of dk with polybar on a dual vertical stacked monitor setup, While everything works great except a few minor issues, The main issue I have right now is the polybar's load right where they should, Yet when I open a new window on my top monitor with two polybars, 1 polybar on top and one on the bottom, The bottom bar overlaps the windows that I have opened on any ws on that particular monitor, Since I am new to dk I was hoping is that I have missed an option to solve the window width/heights on a particular monitor?

I am a normal user of polybar with i3wm and wanted to try something new, Everything works perfect with polybar and i3wm, So I am between this being a dk issue or polybar, Since there are no logs visible on either it is tough to diagnose, I recently posted this in polybar repo. https://github.com/polybar/polybar/issues/3129

**Comment by ACR-Jeff** [comment]
I have tested this issue for some time, It appears dk's config file doesn't play well with including bash scripts, I reconfigured my autostart scriptt and my polybar launcher script from bash to shell, Now I can get the windows to appear normally after a restart of my system, Load a window and the window still isn't above polybar until after I refresh dk's config file. Then it works as it should.

**Comment by natemaia** [comment]
Hello, I'll look into it over the weekend hopefully. Life has been very busy and there's a couple other outstanding issues too. I appreciate the interest and descriptive issue, it helps a lot.

Cheers,
Nathaniel

**Comment by ACR-Jeff** [comment]
> Hello, I'll look into it over the weekend hopefully. Life has been very busy and there's a couple other outstanding issues too. I appreciate the interest and descriptive issue, it helps a lot.
> 
> Cheers, Nathaniel

Thank you for your response and great window manager, No worries, I understand. Have a great weekend.

**Comment by ACR-Jeff** [comment]
Well, I have restored a previous snapshot of my original wm, I couldn't wait due to this being a daily, I may come back to it on another drive or system, I do find your wm very interesting and easy to configure. Thank you

**Comment by natemaia** [comment]
Sorry to hear. Life is just really grinding me down right now, just blew my transmission over the weekend and struggling with everything. I'm really sorry for not being able to address this and apologies for the issues, I completely understand.

Thanks for checking it out, when I get this resolved (eventually I will) I'll post back here if you'd like.

Cheers

**Comment by natemaia** [comment]
Hello again @ACR-Jeff, I believe I resolved the issue with multiple bars on one monitor and it was indeed on dk's side. I wasn't applying the struts correctly.

I know you've moved back to i3 but I'd appreciate a little test to verify it is correct.

Cheers
